version: '3'
services:
  resizer:
    build: resizer
    depends_on:
      - downloader-cache
  resizer-cache:
    image: jonbaldie/varnish
    volumes:
      - ./resizer-cache-default.vcl:/etc/varnish/default.vcl
    depends_on:
      - resizer
    ports:
      - 80:80
  downloader:
    build: downloader
  downloader-cache:
    image: jonbaldie/varnish
    volumes:
      - ./downloader-cache-default.vcl:/etc/varnish/default.vcl
    depends_on:
      - downloader
